# Generated by Django 4.1.1 on 2022-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[('USR', 'Usuario'), ('ADM', 'Administrador')], default='USR', max_length=3)),
                ('text', models.TextField()),
            ],
        ),
    ]
